#!/usr/bin/env python3
"""Generate match_type backfill SQL from the HLTV demo archive's type prefixes.

Generator only: reads a demo filename listing, writes UPDATE statements to
stdout, and never touches a database or the network. Review the output, then
apply it by hand the way sql/repair_backfill_match_type_13community.sql is
applied.

The HLTV recorder names every match demo `<type>_<matchid>_h<half>-...` with a
lowercase type prefix (ktp, scrim, 12man, draft, ktpot, draftot), so the
archive is an authoritative matchid -> type mapping for every match that got a
demo -- including the epoch-SITE ids whose type is not derivable from the id
itself. Produce the listing on the data server, then run this locally:

    find /home/hltvserver/hlds/dod/demos -name '*.dem' > demo-listing.txt
    python3 scripts/backfill-match-type-from-demos.py demo-listing.txt > backfill.sql

Two safety properties:
  * a match id seen under more than one type prefix is reported on stderr and
    skipped -- no guessing
  * every UPDATE is guarded on `match_type IS NULL`, so a value the daemon has
    since written from the wire is never overwritten
"""

import re
import sys

# KTPMatchHandler MatchType enum, mirrored by the HLTV recorder's file prefixes.
TYPE_ENUM = {
    "ktp": 0,
    "scrim": 1,
    "12man": 2,
    "draft": 3,
    "ktpot": 4,
    "draftot": 5,
}

# <type>_<matchid>_h<half>-<stamp>-<map>.dem  -- matchid itself may contain '-'
# (1.3-6076-ATL1) or '.' but never '_', which is what makes the split reliable.
DEMO_RE = re.compile(
    r"(?:^|/)(ktp|scrim|12man|draft|ktpot|draftot)_([^_/]+)_h\d+-", re.IGNORECASE
)


def harvest(lines):
    mapping = {}
    conflicts = set()
    for line in lines:
        m = DEMO_RE.search(line.strip().replace("\\", "/"))
        if not m:
            continue
        type_str, match_id = m.group(1).lower(), m.group(2)
        enum = TYPE_ENUM[type_str]
        if match_id in mapping and mapping[match_id] != enum:
            conflicts.add(match_id)
        else:
            mapping[match_id] = enum
    for match_id in conflicts:
        del mapping[match_id]
    return mapping, conflicts


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    with open(sys.argv[1], encoding="utf-8", errors="replace") as fh:
        mapping, conflicts = harvest(fh)
    if not mapping:
        sys.exit("no demo filenames matched -- is this the right listing?")
    for match_id in sorted(conflicts):
        print(f"-- skipped {match_id}: seen under more than one type prefix", file=sys.stderr)

    print("-- Generated by scripts/backfill-match-type-from-demos.py -- review before applying.")
    print(f"-- {len(mapping)} match ids mapped, {len(conflicts)} conflicting ids skipped.")
    print("-- Dry run:")
    print("SELECT COUNT(*) AS rows_still_null FROM ktp_matches WHERE match_type IS NULL;")
    for match_id in sorted(mapping):
        if "'" in match_id or "\\" in match_id:
            print(f"-- skipped unsafe match id {match_id!r}", file=sys.stderr)
            continue
        print(
            "UPDATE ktp_matches SET match_type = {} "
            "WHERE match_type IS NULL AND match_id = '{}';".format(mapping[match_id], match_id)
        )
    print("SELECT match_type, COUNT(DISTINCT match_id) AS matches FROM ktp_matches GROUP BY match_type;")


if __name__ == "__main__":
    main()
